### ISSUE TITLE
网络请求错误

### ISSUE THREAD

**Issue by Chanyon** [readonlylink/readonlylink#1]
![error](https://user-images.githubusercontent.com/40350332/226602388-a8322592-942a-43a8-a642-63e319ef7737.JPG)

**Comment by xieyuheng** [comment]
@Chanyon 需要用这个连接： https://raw.githubusercontent.com/GuoYaxiang/craftinginterpreters_zh/main/content/26.%E5%9E%83%E5%9C%BE%E5%9B%9E%E6%94%B6.md

https://readonly.link/articles/https://raw.githubusercontent.com/GuoYaxiang/craftinginterpreters_zh/main/content/26.%E5%9E%83%E5%9C%BE%E5%9B%9E%E6%94%B6.md

**Comment by xieyuheng** [comment]
也就是要用 https://raw.githubusercontent.com/

**Comment by xieyuheng** [comment]
另外，这个连接国内没法访问， github 没墙，但是 github 的这个 CDN 墙了。

想要分享内容，建议用 https://netlify.com/

**Comment by Chanyon** [comment]
> 另外，这个连接国内没法访问， github 没墙，但是 github 的这个 CDN 墙了。
> 
> 想要分享内容，建议用 https://netlify.com/

了解了，我说开梯子也不能访问。
